### ISSUE TITLE
Find more public shaders

### ISSUE THREAD

**Issue by sbtoonz** [heinermann/ValheimExportHelper#1]
Hey bud

I have more fixed shaders for you

ToonDeferredShading2017.shader
HiddenDofDX11Dof.shader
CustomLitGui.shader
HiddenDofDepthOfFieldHdr.shader

I would share the lux lit particles one but its a paid asset
[Assets.Resources.zip](https://github.com/heinermann/ValheimExportHelper/files/9260461/Assets.Resources.zip)
[Assets.Shader.zip](https://github.com/heinermann/ValheimExportHelper/files/9260467/Assets.Shader.zip)
[HiddenSunShaftsComposite.zip](https://github.com/heinermann/ValheimExportHelper/files/9260474/HiddenSunShaftsComposite.zip)

**Comment by sbtoonz** [comment]
Sources:
https://gist.github.com/xDavidLeon/690fffea93dde2d3f47c19ea87a19b02
https://github.com/microsoft/Imagine_fudge-roll/tree/master/Fudge%20Roll/assets/standard%20assets/effects/imageeffects/shaders

**Comment by sbtoonz** [comment]
Realized you probably don't need the HLSL format of these shaders

**Comment by heinermann** [comment]
The shaders are still owned by IronGate (??), I don't know how much of it would be copyright violation.

**Comment by sbtoonz** [comment]
That's why I cited the open source repos the hlsl versions were sourced from :)

**Comment by sbtoonz** [comment]
Their Custom/* shaders are all in house produced it appears 

The other ones are sourced from these places it appears 

Lux lit is paid in the store it costs like 20$

**Comment by heinermann** [comment]
Oh I see thanks, will check it later

**Comment by heinermann** [comment]
Name | Source
-- | --
HiddenBlitCopyHDRTonemap | https://github.com/repalash/Open-Shaders/blob/master/Engines/Unity/Builtin/DefaultResourcesExtra/Internal-BlitCopyHDRTonemap.shader
HiddenDofDepthOfFieldHdr | https://github.com/microsoft/Imagine_fudge-roll/blob/master/Fudge%20Roll/assets/standard%20assets/effects/imageeffects/shaders/_DepthOfField/DepthOfFieldScatter.shader
HiddenDofDX11Dof | https://github.com/microsoft/Imagine_fudge-roll/blob/master/Fudge%20Roll/assets/standard%20assets/effects/imageeffects/shaders/_DepthOfField/DepthOfFieldDX11.shader
HiddenInternal-Loading | https://github.com/repalash/Open-Shaders/blob/master/Engines/Unity/Builtin/DefaultResources/Internal-Loading.shader
HiddenInternal-UIRDefaultWorld | https://github.com/repalash/Open-Shaders/blob/master/Engines/Unity/Builtin/DefaultResourcesExtra/UIElements/Internal-UIRDefaultWorld.shader
HiddenSimpleClear | https://github.com/microsoft/Imagine_fudge-roll/blob/master/Fudge%20Roll/assets/standard%20assets/effects/imageeffects/shaders/SimpleClear.shader
HiddenSunShaftsComposite | https://github.com/microsoft/Imagine_fudge-roll/blob/master/Fudge%20Roll/assets/standard%20assets/effects/imageeffects/shaders/SunShaftsComposite.shader
Lux Lit Particles Bumped | https://assetstore.unity.com/packages/vfx/particles/lux-lit-particles-138052
ParticlesStandard Surface2 | Modified from https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/Particle%20Standard%20Surface.shader
ParticlesStandard Unlit2 | Modified from https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/Particle%20Standard%20Unlit.shader
Standard TwoSided | Modified from https://github.com/TwoTailsGames/Unity-Built-in-Shaders/blob/master/DefaultResourcesExtra/Standard.shader
ToonDeferredShading2017 | https://gist.github.com/xDavidLeon/690fffea93dde2d3f47c19ea87a19b02#file-toondeferredshading2017-shader
UnlitDepthWrite |  
UnlitLighting |

**Comment by sbtoonz** [comment]
Let me find the articles about Standard TwoSided 
it was a gist or git repo by unity specifically

**Comment by sbtoonz** [comment]
https://gist.github.com/jminor/6a14271368e57b84c136d94906ae6603

Here is the one for standard TwoSided

**Comment by heinermann** [comment]
> https://gist.github.com/jminor/6a14271368e57b84c136d94906ae6603
> 
> Here is the one for standard TwoSided

This one isn't quite right, it's missing Properties (i.e. `_GlossMapScale`, `_GlossyReflections`, `_Mode`, `_ZWrite`, etc)

I think `ParticlesStandard Surface2`, `ParticlesStandard Unlit2`, and `Standard TwoSided` are all originally Unity shaders just slightly modified.

**Comment by sbtoonz** [comment]
I am rooting around for where I found the copy we have been using. I believe it was merely the standard shader with a VFACE pass added

**Comment by heinermann** [comment]
Added the known ones with 100% matching properties in 9430d38197c9.

**Comment by heinermann** [comment]
We still need, if they exist (probably more small edits of other free shaders)

- UnlitDepthWrite
- UnlitLighting

We can also find out how to modify the following to be similar to the game's version (since they are minor edits of free shaders, recreating the edits to be similar is ok):

- ParticlesStandard Surface2
- ParticlesStandard Unlit2
- Standard TwoSided

**Comment by heinermann** [comment]
As of 788c93834a12e4693464852815767602e7a1c196 I decided to remove the public shaders.

**Comment by heinermann** [comment]
Included these in the notes in 904cc6588f16b6ab5042943a37ccfec26b28b551
