### ISSUE TITLE
UnzipExtension not found when using Dll Export Without Renaming

### ISSUE THREAD

**Issue by heinermann** [heinermann/ValheimExportHelper#12]
> Assets\Scripts\Editor\RestoreShadersOnSceneLoad.cs(16,9): error CS0103: The name 'UnzipExtension' does not exist in the current context

This error occurs when loading a project using the **Dll Export Without Renaming** Script Export Format.

**Comment by sbtoonz** [comment]
Was worried about using the extension concept

**Comment by heinermann** [comment]
For the `ZipFile` problem there's this answer https://forum.unity.com/threads/c-compression-zip-missing.577492/

> These types are in the System.IO.Compression.FileSystem.dll assembly, which is not passed as a reference by Unity to the C# compiler by default. You can create a file named mcs.rsp in the Assets/ directory of your Unity project to let the C# compiler know you want this additional reference.

Trying it out.

**Comment by heinermann** [comment]
Worked beautifully.
