### ISSUE TITLE
Valheim export helper not detecting the Valheim installation

### ISSUE THREAD

**Issue by StainlessSteelPhoenix** [heinermann/ValheimExportHelper#16]
I have a Steam folder on my m.2 SSD with Valheim (applied HD Valheim mod to globalgamemanagers.assets, sharedassets1.assets, sharedassets3.assets and sharedassets4.assets files)
I extracted Asset ripper on a HDD drive. 

Getting following messages in the console:

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.2.2.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: 08/18/2022 16:18:04
System : UTC Compile Time: Thu Aug  4 06:50:41 UTC 2022
Plugin : Loading plugins...
Plugin : Found assembly at E:\Valheim HD +\Prog\Asset ripper 0.2.2.0\Plugins\ValheimExportHelper.dll
Plugin : [ValheimExportHelper] Initializing... Waiting to detect game.
Plugin : Initialized plugin: ValheimExportHelper
Plugin : Finished loading plugins.
System : Loading locale en_US.json

Should I move the Asset ripper folder, or restore the game files to Vanilla?

**Comment by heinermann** [comment]
It doesn't detect where Valheim is, you need to open the Valheim folder with AssetRipper

**Comment by heinermann** [comment]
See [Valheim Unity Project Guide](https://github.com/Valheim-Modding/Wiki/wiki/Valheim-Unity-Project-Guide)

**Comment by heinermann** [comment]
Since there's no reply and the log doesn't show any opening of the game directory I'm closing this
