### ISSUE TITLE
Wrong build artifacts being zipped in release script

### ISSUE THREAD

**Issue by hyoza** [heinermann/ValheimExportHelper#20]
Dear Heinermann.

There seems to be a problem with missing dependencies in the compressed file of the released 1.2.0 version. The reason I thought so is that your 1.2.0 helper's compressed file size is 110k, which is small compared to the 31MB of the 1.1.0 version. I am reading the guide article https://github.com/Valheim-Modding/Wiki/wiki/Valheim-Unity-Project-Guide. I used asset ripper 0.2.2.0 and your helper 1.1.0 and it was good. However, if you use the latest version of 1.2.0 help and asset ripper 0.2.3.0, it will not work properly. It seems that it is not an exported dll including all dependencies. I want to build with your latest version of the source, but I think it will be faster to ask you than that, so I leave a message like this.

Thanks to heinermann's project.
Regards,

Hyoja

**Comment by heinermann** [comment]
~~The Yaml dependency should be included in AssetRipper. So it doesn't make sense to include a dependency that is already there.~~

~~What exactly isn't working? I am able to run it fine as is. Which OS? Can you share the log?~~

I see

**Comment by heinermann** [comment]
The automatic release generation is not zipping/uploading the correct build artifacts.

**Comment by heinermann** [comment]
I've replaced the zip for that release.

**Comment by hyoza** [comment]
![image](https://user-images.githubusercontent.com/4544377/187380070-90a4e066-9474-4f2b-b8b8-2cf379b85e3b.png)

thx heinermann good works.

have a nice day.
