### ISSUE TITLE
Disable Motion Blur automatically

### ISSUE THREAD

**Issue by heinermann** [heinermann/ValheimExportHelper#9]
The scenes by default will look fuzzy or blurry. This is a bad experience, we should write wherever the settings are stored to disable **Motion Blur** (*without modifying the scene or ripped data*) which makes it look normal.

**Comment by heinermann** [comment]
In *Windows*, this is in `HKEY_CURRENT_USER\SOFTWARE\Unity\UnityEditor\IronGate\Valheim` with the key `MotionBlur_h2158824370`. No idea what the `_h2158824370` is or how to get it. Each key has its own code attached to it and the normal key without it won't change the default setting.

We can also manually toggle it once when a scene is finished loading (`Settings.instance.m_motionblurToggle.isOn = false`  followed by `GameCamera.instance.ApplySettings()` probably). Or use `PlayerPrefs.SetInt("MotionBlur", PlayerPrefs.GetInt("MotionBlur", 0))` prior to `LoadSettings` being called.

**Comment by sbtoonz** [comment]
i THOUGHT motion blur was set in the PostProcessing scriptable object ... leme dig around for it

**Comment by sbtoonz** [comment]
Look at file 

Assets\MonoBehaviour\ingame.asset

the context of this file is a scriptable object which is inherited by the post processing component and contains the motion blur settings 

```
motionBlur:
    m_Enabled: 1
    m_Settings:
      shutterAngle: 150
      sampleCount: 10
      frameBlending: 0
```

Simply tick m_Enabled => 0

and this will force motion blur off

**Comment by heinermann** [comment]
Ah neat, thanks. Adding this change. It can also be toggled back on with in-game settings too which is exactly what I want.

**Comment by heinermann** [comment]
Added in 5a262094f1ef780
